version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=travel_agency
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2300:2300"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/travel_agency?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
